Save to GitHub
PIP-Technical-Team/pipfun pull request #2
Opened 2024-07-10 13:19 UTC by shahronak47

Hi Andres, 

This PR aims to create a new function called `save_to_gh` which aims to save the data to GitHub. This is written mostly to save GDP  data to GitHub for this task. https://app.clickup.com/t/8688xw9p1

2024-07-17 21:20 UTC, randrescastaneda requested changes
HI @shahronak47 , 

Thank you so much. I added a couple of minor comments. 

Thank you so much. 

Best,

2024-07-17 21:20 UTC, randrescastaneda commented on R/save_to_gh.R
> +  )
Hi @shahronak47 , 

Thanks. Make sure you use the `.token` argument as we do here: https://github.com/PIP-Technical-Team/pipfun/blob/e9a53060c396c4ca6e090f15b57a26f91e82084d/R/load_from_gh.R#L108

2024-07-17 21:20 UTC, randrescastaneda commented on tests/testthat/test-save_to_gh.R
> +  mockery::stub(save_to_gh, "gh::gh", NULL)
Hi @shahronak47 
The `mockery` package is being replaced by the new mocking tools in testthat: https://testthat.r-lib.org/reference/local_mocked_bindings.html

You can take a look at how we use them in the `pipapi` for some testing
1. For specific calls: https://github.com/PIP-Technical-Team/pipapi/blob/c1267780f08af67e18c0023ecfcfae887e203587/tests/testthat/test-ui_poverty_indicators.R#L18-L27
2. For complete tests: https://github.com/PIP-Technical-Team/pipapi/blob/c1267780f08af67e18c0023ecfcfae887e203587/tests/testthat/test-pip_grp_logic.R#L27-L29 


Of course, if these `testhat` functions do not work in your case, please keep using `mockery`. 😉 
Thanks.

2024-07-18 13:42 UTC, shahronak47 commented on R/save_to_gh.R
> +  )
Done.

2024-07-18 13:43 UTC, shahronak47 commented on tests/testthat/test-save_to_gh.R
> +  mockery::stub(save_to_gh, "gh::gh", NULL)
Thanks, I didn't know `mockery` was superseded. Replaced `mockery::stub` with `local_mocked_bindings`

2024-07-18 13:58 UTC, randrescastaneda requested changes
Hi @shahronak47 , 

please take a look at the circular dependency problem we have with `pipfun`. 

Thanks.

2024-07-18 13:58 UTC, randrescastaneda commented on R/save_to_gh.R
> +      content = pipaux:::convert_df_to_base64(df)
hi @shahronak47 , 

I think we have a circular dependency problem here. `pipaux` depends on `pipfun` (see [here](https://github.com/PIP-Technical-Team/pipaux/blob/88429b29adc17d02d6feae15784fec73dfe2b25a/DESCRIPTION#L51)). 

It think the best option is to move `convert_dr_to_base64()` to `pipfun` from `pipaux`.  What do you think?

2024-07-18 15:35 UTC, shahronak47 commented on R/save_to_gh.R
> +      content = pipaux:::convert_df_to_base64(df)
This makes sense, I have added an update to copy the function here.

2024-07-18 21:09 UTC, randrescastaneda approved these changes
Fantastic

2024-07-18 21:10 UTC, merged